
project_id = "your-project-id"

[api]
port = 54321
schemas = ["public", "storage", "extensions"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[functions]
[functions.ai-model-proxy]
verify_jwt = true

[functions.ai-reasoning]
verify_jwt = true

[functions.google-search]
verify_jwt = true

[functions.query-knowledge-base]
verify_jwt = true

[functions.upload-knowledge]
verify_jwt = true

[functions.web-scraper]
verify_jwt = true
