
# This is the configuration for your Supabase project.
project_id = "dwescgkujhhizyrokuiv"

[api]
enabled = true
port = 54321

[db]
port = 54322

[auth]
enabled = true
port = 9999
uri = "postgresql://postgres:postgres@localhost:54322/postgres"

[storage]
enabled = true

[functions]
[functions.ai-reasoning]
verify_jwt = true
[functions.ai-model-proxy]
verify_jwt = true
