
project_id = "dwescgkujhhizyrokuiv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"

[analytics]
enabled = false

[experimental]
includes_preview_migrations = false

[[migrations.templates]]
path = "supabase/templates/database.sql"
placeholders = []

[migrations.template_config]
use_database_migrations = true

[functions.query-knowledge-base]
verify_jwt = false

[functions.upload-knowledge]
verify_jwt = false
