
import {
  ArrowRight,
  Book,
  Brain,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Copy,
  Download,
  Edit2,
  ExternalLink,
  File,
  FileSearch,
  Folder,
  Github,
  Globe,
  HelpCircle,
  Info,
  KanbanSquare,
  Key,
  Loader2,
  Lock,
  Mail,
  MessageSquare,
  MoreHorizontal,
  Plus,
  PlusCircle,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  SidebarClose,
  SidebarOpen,
  Terminal,
  Trash2,
  User,
  UserPlus,
  Users,
  Zap,
} from "lucide-react";

import JiraIcon from "./icons/JiraIcon";

export const Icons = {
  arrowRight: ArrowRight,
  book: Book,
  brain: Brain,
  checkCircle2: CheckCircle2,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  copy: Copy,
  download: Download,
  edit2: Edit2,
  externalLink: ExternalLink,
  file: File,
  fileSearch: FileSearch,
  folder: Folder,
  github: Github,
  globe: Globe,
  helpCircle: HelpCircle,
  info: Info,
  jira: JiraIcon,
  key: Key,
  loader2: Loader2,
  lock: Lock,
  mail: Mail,
  messageSquare: MessageSquare,
  moreHorizontal: MoreHorizontal,
  plus: Plus,
  plusCircle: PlusCircle,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  share2: Share2,
  shield: Shield,
  shieldAlert: ShieldAlert,
  sidebarClose: SidebarClose,
  sidebarOpen: SidebarOpen,
  terminal: Terminal,
  trash2: Trash2,
  user: User,
  userPlus: UserPlus,
  users: Users,
  zap: Zap,
  "kanban-square": KanbanSquare,
};
