// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwescgkujhhizyrokuiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3ZXNjZ2t1amhoaXp5cm9rdWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODMwNjYsImV4cCI6MjA2MjQ1OTA2Nn0.tktvFI92_RhKWtOtP3yv5TEgN7ATopSgNBNuQ_vbsSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);